// Invented examples only. Never commit scraped personal data to the public repo.
const base = { kind:'room_offer',city:'חיפה',cityBasis:'post',rentalType:'regular',address:'',rooms:[],entryText:'',endText:'',existingRoommates:null,totalOccupants:null,furnitureText:'',shabbatPolicy:'unknown',kosherPolicy:'unknown',billsText:'',freeText:'',reason:'הצעת חדר בדירת שותפים קיימת',warnings:[],evidence:[] };
const example = (id,text,result) => ({id,post:{text,sourceUrl:'',groupCity:result.city || 'חיפה',postedAt:'',demo:true},result:{...base,...result},model:'דוגמה מוכנה — לא הופעל AI',provider:'demo'});
export const demoPosts = [
  example('demo-room','דוגמה להמחשה: מתפנה חדר בדירת 3 שותפים בחיפה. שני שותפים נשארים. 1,600 ₪ לחודש, לא כולל חשבונות. כניסה 1/10. בחדר מיטה וארון. חוזה לשנה. מרפסת ומקלט בבניין.',{address:'חיפה',rooms:[{label:'חדר עם מיטה וארון',monthlyRentIls:1600,priceEvidence:'1,600 ₪ לחודש'}],entryText:'1/10',existingRoommates:2,totalOccupants:3,furnitureText:'מיטה וארון בחדר',billsText:'לא כולל חשבונות',freeText:'מרפסת ומקלט בבניין.',warnings:['שנת הכניסה לא צוינה'],evidence:[{field:'existingRoommates',quote:'שני שותפים נשארים'}]}),
  example('demo-sublet','דוגמה להמחשה: מסבלטים חדר בדירת שותפים בתל אביב מ־1/11/2026 עד 30/11/2026. 2,400 ₪ לחודש כולל חשבונות. החדר מרוהט מלא.',{city:'תל אביב',rentalType:'sublet',rooms:[{label:'חדר מרוהט',monthlyRentIls:2400,priceEvidence:'2,400 ₪ לחודש'}],entryText:'1/11/2026',endText:'30/11/2026',furnitureText:'חדר מרוהט מלא',billsText:'כולל חשבונות'}),
  example('demo-seeker','דוגמה להמחשה: מחפש חדר בדירת שותפים בבאר שבע, או שותפים לחפש איתם דירה. כניסה במהלך נובמבר.',{city:'באר שבע',kind:'room_seeker',rentalType:'unknown',entryText:'במהלך נובמבר',reason:'מחפש חדר; אין חדר מוצע',freeText:'מעוניין גם בחיפוש דירה משותף.'}),
  example('demo-whole','דוגמה להמחשה: דירה שלמה בירושלים, 4 חדרים, 6,000 ₪ לחודש. מתאימה לשותפים.',{city:'ירושלים',kind:'whole_apartment',rentalType:'unknown',reason:'דירה שלמה; אין הצעת חדר נפרד'}),
];
