import ReportProfileButton from '@/components/safety/ReportProfileButton';
import React,{useEffect,useRef,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {roomHub} from '@/api/roomHub';
import {roomText as rt,useRoomLocale} from '@/lib/room-i18n';
export default function PublisherDiscover(){useRoomLocale();const navigate=useNavigate(),start=useRef(null);const [data,setData]=useState(null),[rooms,setRooms]=useState([]),[index,setIndex]=useState(0),[selected,setSelected]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{Promise.all([roomHub('account'),roomHub('candidates')]).then(([a,c])=>{const active=a.rooms.filter(r=>r.status==='published');setRooms(active);setSelected(active[0]?.id||'');setData(c.records);}).catch(e=>setError(e.response?.data?.error||e.message||'hub.failed'));},[]);
 const p=data?.[index];async function send(){setBusy(true);try{const x=await roomHub('offer',{room_id:selected,profile_id:p.id});navigate('/RoomChat?offerId='+encodeURIComponent(x.id));}catch(e){setError(e.response?.data?.error||e.message||'hub.failed');}finally{setBusy(false);}}
 return <section className="rr rh-publisher-discover"><h1>{rt('hub.find_tenants')}</h1><p>{rt('hub.swipe_offer')}</p><Link className="rr-add" to="/Profile">{rt('hub.partner_account')}</Link><Link to="/RoomAccount">{rt('hub.my_rooms')}</Link>{error&&<p role="alert">{rt(error)}</p>}{!data&&!error&&<p>{rt('hub.loading')}</p>}{data&&!p&&<p>{rt('hub.no_candidates')}</p>}
 {p&&<article className="rr-card" onPointerDown={e=>{start.current={x:e.clientX,y:e.clientY};}} onPointerUp={e=>{if(!start.current)return;const dx=e.clientX-start.current.x,dy=e.clientY-start.current.y;start.current=null;if(Math.abs(dy)>Math.abs(dx))return;if(dx>80)setConfirm(true);if(dx< -80)setIndex(i=>i+1);}} style={{touchAction:'pan-y'}}>
 {p.photos?.[0]&&<img className="rh-candidate-photo" src={p.photos[0]} alt={p.name}/>}<h2>{p.name}{p.age?' · '+p.age:''}</h2><p>{p.about_me}</p><ReportProfileButton profileId={p.id}/><div className="rh-tabs"><button onClick={()=>setIndex(i=>i+1)}>{rt('hub.skip')}</button><button className="rr-primary" disabled={!rooms.length} onClick={()=>setConfirm(true)}>{rt('hub.offer_room')}</button></div></article>}
 {data&&!rooms.length&&<p>{rt('hub.publish_first')}</p>}{confirm&&p&&<div className="rr-card" role="dialog" aria-label={rt('hub.offer_room')}><p>{rt('hub.offer_explanation')}</p>{rooms.length>1?<label>{rt('hub.choose_room')}<select value={selected} onChange={e=>setSelected(e.target.value)}>{rooms.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>:<strong>{rooms[0]?.title}</strong>}<button disabled={busy||!selected} onClick={send}>{rt('hub.send_offer')}</button><button disabled={busy} onClick={()=>setConfirm(false)}>{rt('hub.cancel')}</button></div>}</section>;
}
